# This file was generated by GoReleaser. DO NOT EDIT.
cask "bragfile" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "672338db093a0a93c4dfaf4e2d1c6c58f69c861a491c9e73269409e8f4009b42"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0f8ed350579d07da2465b1c2edab7c983d391ffc939c7b18ade3e6194cad65a"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bdd978e3fa51a11901756d01f4d06c9d98b89c0780bdc04fbcb7585626023fce"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9ea59d5922386765818cc183f0d0efe414707dfc972e6ef6409f86102635949"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bragfile"
  desc "Local-first Go CLI to capture and retrieve career-worthy moments."
  homepage "https://github.com/jysf/bragfile000"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brag"

  # No zap stanza required

end
