# This file was generated by GoReleaser. DO NOT EDIT.
cask "bragfile" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "3dd9d57ba45b0ef0dc65179e5deacb700e05322350a7eac6d0143f668201d90e"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6070b1ef813dcacc1686b3a9a94764c3c70cd3083765d039ff13d69ddbfc589e"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a72a40484bd446e9e7f8078e3b84a9e1425b100b402f4e88e589598304e6588c"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9756e0dd7197fb3c88304339be3a35171bdf3c46ada10bc7e42c42320014a855"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bragfile"
  desc "Local-first Go CLI to capture and retrieve career-worthy moments."
  homepage "https://github.com/jysf/bragfile000"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brag"

  # No zap stanza required

end
