# This file was generated by GoReleaser. DO NOT EDIT.
cask "bragfile" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "c7102e1549ad9efbcbbc5d426bf263d3d6222d084f2cbc801ea0eeb0bed83c29"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad4226909d3558743a2789a6eccf1ad3acc331e88bd97923c22fadd4c2b5346d"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "149ccf82cd51c6f22cee7ea891822cb9acb085a686c81472ea4df8f6dcb92bdb"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a25255b91eacabcedbf5295805d9b88d4f3723e454df5f96a94a58bfe1b08cf"
      url "https://github.com/jysf/bragfile000/releases/download/v#{version}/bragfile000_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bragfile"
  desc "Local-first Go CLI to capture and retrieve career-worthy moments."
  homepage "https://github.com/jysf/bragfile000"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brag"

  # No zap stanza required

end
